version: '3'

services:
    bdd:
      build: ./bdd/
      volumes:
        - ./bdd/bdd_files/:/data/db
      ports:
        - 27017:27017
    server:
      build: ./server/
      volumes:
        - ./server:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 8081:8081
      depends_on:
        - bdd
        - app
    app:
      build: ./app/
      volumes:
        - ./app:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 80:3000
      depends_on:
        - bdd